services:
  chatbot_history:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./chatbot_history/.env
    ports:
      - "8003:8003"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
    tty: true
    stdin_open: true

  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./chatbot/.env
    ports:
      - "8001:8001"
    tty: true
    stdin_open: true

  auth:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./Auth/Auth/.env
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
    tty: true
    stdin_open: true

  ngrok:
    image: ngrok/ngrok:alpine
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: start --all --config /etc/ngrok.yml
    ports:
      - "4040:4040"
