version: '3.8'

services:
  backend_services:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
      - "8001:8001" 
      - "8002:8002" 
      - "8003:8003"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD} # Consider using Docker secrets for passwords in production
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
    depends_on:
      []
    tty: true
    stdin_open: true


volumes:
  postgres_data:
