services:
  django:
    build: .
    container_name: chatbot_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    container_name: redis-service
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
     
    
    
    
