version: '3.8'
services:
  backend:
    build: .
    container_name: chatbot_backend
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3
    volumes:
      - .:/app
    command: sh -c "python manage.py migrate && gunicorn chatbot_backend.wsgi:application --bind 0.0.0.0:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
