name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'chatbot-frontend/**'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: chatbot-frontend

      - name: Build frontend
        run: npm run build
        working-directory: chatbot-frontend

      - name: Install Vercel CLI (for debugging or local use)
        run: npm install -g vercel
        working-directory: chatbot-frontend

      - name: Deploy to Vercel
        run: npx vercel --prod --yes
        working-directory: chatbot-frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
